Application.Northwind.MvcWebUI/Models/CategoryListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Northwind.Entities.Concrete;

namespace Application.Northwind.MvcWebUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }
    }
}

Application.Northwind.MvcWebUI/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Northwind.Entities.Concrete;

namespace Application.Northwind.MvcWebUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> ProductlList { get; set; }
        public int PageCount { get; set; }
        public int PageSize { get; set; }
        public int CurrentCategory { get; set; }
        public int CurrentPage { get; set; }
    }
}

Application.Northwind.MvcWebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Northwind.Business.Abstract;
using Application.Northwind.MvcWebUI.Services;
using Microsoft.AspNetCore.Mvc;

namespace Application.Northwind.MvcWebUI.Controllers
{
    public class CartController : Controller
    {
        private ICartSessionService _cartSessionService;
        private ICartService _cartService;
        private IProductService _productService;

        public CartController(IProductService productService, ICartService cartService, ICartSessionService cartSessionService)
        {
            _cartSessionService = cartSessionService;
            _cartService = cartService;
            _productService = productService;
        }

        public IActionResult AddToCart(int productId)
        {
            var productToBeAdded = _productService.GetById(productId);

            var cart = _cartSessionService.GetCart();

            _cartService.AddToCart(cart,productToBeAdded);
            _cartSessionService.SetCart(cart);

            TempData.Add("message", String.Format("Your product {0} was successfully added to the cart!!",productToBeAdded.ProductName));
            return RedirectToAction("Index", "Product");
        }
    }
}

Application.Northwind.MvcWebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Northwind.Business.Abstract;
using Application.Northwind.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace Application.Northwind.MvcWebUI.Controllers
{
    public class ProductController:Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public ActionResult Index(int page=1,int category = 0)
        {
            int pageSize = 10;
            var products = _productService.GetByCategory(category);
            ProductListViewModel model = new ProductListViewModel()
            {
                ProductlList = products.Skip((page-1)*pageSize).Take(pageSize).ToList(),
                PageCount = (int)Math.Ceiling(products.Count/(double)pageSize),
                PageSize = pageSize,
                CurrentCategory = category,
                CurrentPage = page
            };
            return View(model);
        }
    }
}

Application.Northwind.MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Northwind.Business.Abstract;
using Application.Northwind.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Application.Northwind.MvcWebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

Application.Northwind.MvcWebUI/Views/Product/Index.cshtml
@model Application.Northwind.MvcWebUI.Models.ProductListViewModel

@{
    Layout = "~/Views/_Layout.cshtml";
}
<div>
    <table class="table table-responsive table-striped">
        <tr>
            <td>ProductName</td>
            <td>Category Id</td>
            <td>Unit Price</td>
            <td>Units In Stock</td>
            <td></td>
        </tr>
        @foreach (var product in Model.ProductlList)
        {
            <tr>
                <td>@product.ProductName</td>
                <td>@product.CategoryId</td>
                <td>@product.UnitPrice</td>
                <td>@product.UnitsInStock</td>
                <td><a class="btn btn-xs btn-success" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@product.ProductId">add to cart</a></td>
            </tr>
        }
    </table>
</div>

<product-list-pager current-category="@Model.CurrentCategory"
                    current-page="@Model.CurrentPage"
                    page-count="@Model.PageCount"
                    page-size="@Model.PageSize"></product-list-pager>

Application.Northwind.MvcWebUI/Views/Shared/Components/CategoryList/Default.cshtml
@model Application.Northwind.MvcWebUI.Models.CategoryListViewModel

<div class="list-group">
    @foreach (var category in Model.Categories)
    {
        var css = "list-group-item";
        if (category.CategoryId == Model.CurrentCategory)
        {
            css += " active";
        }
        <a href="/product/index?category=@category.CategoryId" class="@css">@category.CategoryName</a>
    }
</div>

Application.Northwind.MvcWebUI/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="/node_modules/bootstrap/dist/js/bootstrap.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">WebSiteName</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Inicio <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Opcion 1</a>
                            </li>
                            <li>
                                <a href="#">Opcion 2</a>
                            </li>
                            <li>
                                <a href="#">Opcion 3</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Pagina 2</a>
                    </li>
                    <li>
                        <a href="#">Pagina 3</a>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!--/.container-fluid -->
    </nav>

    <div class="row">
        <div class="col-md-2">

            @await Component.InvokeAsync("CategoryList")
        </div>
        <div class="col-md-10">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-info" role="alert">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
    </div>
    <div>footer</div>
</body>
</html>